website/admin/routes.py
"""Mapping the admin URLs to the code rendering the web page."""

import os

from flask import render_template, redirect, url_for, Blueprint
from flask_login.utils import login_required

from website.task.routes import DIRECTORY_TASKS
from website.task.utils import remove_directory
from website.admin.utils import (
    add_new_user,
    configure_db_records,
    admin_access_required,
    remove_existing_user,
    remove_new_request,
)
from website.models import Request, User
from website import db


admin = Blueprint("admin", __name__)



@admin.route("/admin")
@login_required
@admin_access_required()
def admin_main():
    """The route to admin main panel.

    Returns:
        Renders admin-main.html template.
    """
    return render_template("admin-main.html")


@admin.route("/admin/requests", methods=["GET", "POST"])
@admin_access_required()
def approve_requests():
    """The route for approving requests.

    Returns:
        Renders template with requests management panel.
    """
    requests = Request.query.order_by(Request.date_requested)
    return render_template("admin-approve-requests.html", requests=requests)


@admin.route("/add-user/<int:request_id>")
@admin_access_required()
def add_user(request_id):
    """The route for adding new user.

    Args:
        request_id (int): The request unique identifier.

    Returns:
        Redirects to requests list.
    """
    request_approved = Request.query.get(request_id)
    request_approved.approved = True
    add_new_user(request_approved)
    remove_new_request(request_id)

    return redirect(url_for("admin.approve_requests"))


@admin.route("/admin/users")
@admin_access_required()
def users():
    """The route for managing users.

    Returns:
        Renders a page with users list.
    """
    users = User.query.order_by(User.date_added)
    return render_template("admin-users.html", users=users)


@admin.route("/remove-request/<int:request_id>")
@admin_access_required()
def remove_request(request_id):
    """The route for removing the request.

    Args:
        request_id (int): The request's unique identifier.

    Returns:
        Redirects to modified requests list.
    """
    remove_new_request(request_id)
    return redirect(url_for("admin.approve_requests"))


@admin.route("/admin/remove/<int:user_id>")
@admin_access_required()
def remove_user(user_id):
    """The route for removing the user.

    Args:
        user_id (int): The user's unique identifier.

    Returns:
        Redirects to modified users list.
    """
    remove_existing_user(user_id)
    return redirect(url_for("admin.users"))


@admin.route("/admin/restart-db")
@admin_access_required()
def admin_restart_db():
    """The route for restarting the database.

    Returns:
        Renders admin main panel template.
    """
    db.drop_all()
    db.create_all()
    configure_db_records()
    remove_directory(os.path.abspath(DIRECTORY_TASKS))
    return render_template("admin-main.html")

website/main/routes.py
from flask import render_template, redirect, url_for, Blueprint
from flask_login.utils import login_required


main = Blueprint("main", __name__)


@main.route("/")
def base():
    """The route for redirecting to the login page."""
    return redirect(url_for("auth.index"))


@main.route("/help")
@login_required
def help():
    """The route for rendering help page template."""
    return render_template("help.html")


@main.route("/about")
@login_required
def about():
    """The route for rendering about page template."""
    return render_template("about.html")

website/task/routes.py
"""The routes.py file for routing related to a task."""

import os
from PIL import Image
from flask_login.utils import login_required
from werkzeug.utils import secure_filename

from flask import render_template, url_for, redirect, request, Blueprint, flash
from flask_login import current_user

from website.admin.utils import admin_access_required
from website.task.forms import CreateTaskForm, TaskForm
from website.models import (
    FILE_STATUS,
    DefaultLabel,
    Task,
    TaskDefaultLabel,
    Upload,
    TaskUpload,
)
from website.task.utils import (
    add_new_files,
    check_extension,
    add_default_label,
    get_items_names,
    make_directories,
    process_save_dicom_file,
    process_save_seq_file,
    process_save_video_file,
    remove_db_task_data,
    remove_directory,
)
from website import db


task = Blueprint("task", __name__)


DIRECTORY_TASKS = os.path.abspath("website\\LABEL\\TASKS\\")


@task.route("/admin/manage-tasks", methods=["GET", "POST"])
@login_required
@admin_access_required()
def manage_tasks():
    """The route for managing tasks.

    Returns:
        Renders the template with available tasks and tools for managing or redirects to the route for creating a new task.
    """
    tasks = Task.query.order_by(Task.id)
    task_upload = TaskUpload.query.order_by(TaskUpload.id)
    create_task_form = CreateTaskForm()
    if request.method == "POST":
        tasks_num = len(Task.query.all())
        return redirect(url_for("task.create_task", id=tasks_num + 1))
    return render_template(
        "admin-manage-tasks.html",
        form=create_task_form,
        tasks=tasks,
        task_upload=task_upload
    )


@task.route("/admin/cancel-task/<int:id>", methods=["GET", "POST"])
@login_required
@admin_access_required()
def cancel_task(id):
    """The route for cancelling the specified task. The task is not submitted and not visible on the tasks list.

    Args:
        id (int): The unique task identifier.
    """
    remove_directory(os.path.abspath(DIRECTORY_TASKS + "\\" + str(id)))
    remove_db_task_data(task_id=id)
    return redirect(url_for("task.manage_tasks"))


@task.route("/admin/create-task/<int:id>", methods=["GET", "POST"])
@login_required
@admin_access_required()
def create_task(id):
    """The rout for creating a new task. When submitted, will be visible on the task list and available for users.

    Args:
        id (int): The unique identifier for the newly created task.

    Returns:
        Renders a template with the task's data form or redirects to the tasks list.
    """
    dir_files = os.path.abspath(DIRECTORY_TASKS + "\\" + str(id) + "\\FILES")
    dir_labels = os.path.abspath(DIRECTORY_TASKS + "\\" + str(id) + "\\ANNOTATIONS\\")
    make_directories(dir_files, dir_labels)

    task_form = TaskForm()

    uploads_list = get_items_names(
        query=TaskUpload.query.filter(TaskUpload.task_id == id).all(), table=Upload
    )

    if task_form.validate_on_submit():
        if task_form.create.data:
            if not bool(uploads_list):
                flash("Please upload at least one file in order to create this task.", "warning")
                return redirect(url_for("task.create_task", id=id))
            if task_form.name.data is not None:
                Task.create(id=id, name=task_form.name.data)
            else:
                Task.create(id=id, name="Unnamed")
            return redirect(url_for("task.manage_tasks"))
        if task_form.upload.data:
            if "files[]" not in request.files:
                return redirect(request.url)
            files = request.files.getlist("files[]")
            for file in files:
                if file and check_extension(file.filename):
                    filename = secure_filename(file.filename)
                    extension = filename.rsplit(".", 1)[1].lower()
                    if extension == "seq":
                        camera = dict(task_form.select_camera.choices).get(
                            task_form.select_camera.data
                        )
                        frames = task_form.select_frames.data
                        if frames is None or frames == 0:
                            flash(
                                "Please enter the correct number of frames if a sequence is uploaded.",
                                "warning"
                            )
                            return redirect(url_for("task.create_task", id=id))
                        process_save_seq_file(file, dir_files, filename, camera, frames)
                        add_new_files(id, dir_files)
                    if extension == "mp4":
                        process_save_video_file(file, dir_files, filename, task_id=id)
                    if extension == "dcm":
                        process_save_dicom_file(file, dir_files, filename)
                    upload = Upload(
                        data=file.read(), mimetype=file.mimetype, name=filename
                    )
                    db.session.add(upload)
                    db.session.commit()
                    if upload.id is not None:
                        task_upload = TaskUpload(task_id=id, upload_id=upload.id)
                        db.session.add(task_upload)
                        db.session.commit()
                        if extension not in ("dcm", "mp4", "seq"):
                            img = Image.open(file.stream)
                            img.save(os.path.join(dir_files, filename))
                        if extension in ("mp4", "seq"):
                            os.remove(os.path.join(dir_files, filename))
                            db.session.delete(task_upload)
                            db.session.delete(upload)
                            db.session.commit()
                    flash(filename + " uploaded successfully", "success")
                else:
                    flash(
                        "The uploaded file is not supported."
                        + " Please upload new file with appropriate extension."
                        + " Supported files: 'png', 'jpg', 'jpeg', 'bmp', 'dcm', 'mp4', 'seq'.",
                        "danger",
                    )
                    return redirect(url_for("task.create_task", id=id))
        if task_form.add.data:
            if task_form.default_label.data is not None:
                add_default_label(
                    task_id=id, default_label=task_form.default_label.data
                )

    uploads_list = get_items_names(
        query=TaskUpload.query.filter(TaskUpload.task_id == id).all(), table=Upload
    )

    return render_template(
        "admin-create-task.html",
        id=id,
        form=task_form,
        uploads=uploads_list,
        default_labels=get_items_names(
            query=TaskDefaultLabel.query.filter(TaskDefaultLabel.task_id == id).all(),
            table=DefaultLabel
        ),
    )


@task.route("/task-details/<int:task_id>")
@login_required
@admin_access_required()
def check_task_details(task_id):
    """The route for page displaying files within a selected task.

    Args:
        task_id (int): The task's unique identifier.

    Returns:
        Returns a template with the task's data.
    """
    return render_template("task-details.html", task_id=task_id)


@task.route("/change-task-status/<int:task_id>/<int:status>")
@login_required
@admin_access_required()
def change_task_status(task_id, status):
    """The route for modifying the task's status (possible status: "open", "closed").

    Args:
        task_id (int): The task's unique identifier.
        status (int): THe task's status.

    Returns:
        Redirects to the page for managing tasks.
    """
    task = Task.query.filter(Task.id == task_id, Task.status == status).first()
    task.status ^= 1
    db.session.commit()
    return redirect(url_for("task.manage_tasks"))


@task.route("/change-file-status/<int:task_id>/<int:file_id>/<int:status>")
@login_required
@admin_access_required()
def change_file_status(task_id, file_id, status):
    """The route for modifying file status (possible status: "new", "in progress", "annotated", "closed").

    Args:
        task_id (int): The task's unique identifier.
        file_id (int): The file's unique identifier.
        status (int): The current status of the file within the task.

    Returns:
        Redirects to the files list within a selected task.
    """
    upload = Upload.query.filter(Upload.id == file_id).first()
    if upload.status <= 2:
        upload.status = FILE_STATUS["CLOSED"]
    else:
        upload.status = FILE_STATUS["NEW"]
    db.session.commit()
    return redirect(
        url_for("user.task_files", username=current_user.username, task_id=task_id)
    )


@task.route("/remove-task/<int:task_id>")
@login_required
@admin_access_required()
def remove_task(task_id):
    """The route for removing the task.

    Args:
        task_id (id): The task unique identifier.

    Returns:
        Redirects to the managing tasks section.
    """
    remove_db_task_data(task_id=task_id)
    remove_directory(os.path.abspath(DIRECTORY_TASKS + "\\" + str(task_id)))
    return redirect(url_for("task.manage_tasks"))

website/templates/about.html
{% extends 'base.html' %}

{% block style %}
    <link href="{{ url_for('static', filename='styles/main.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='styles/about-style.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block body %}
    <header>
        {% if current_user.access == 2 %}
            {% include 'includes/_navbar-admin.html' %}
        {% else %}
            {% include 'includes/_navbar-user.html' %}
        {% endif %}
    </header>
    <div class="container-fluid px-5 mt-5">
        <hr>
        <div class="row px-5 mt-5">
            <h4>ELMEDILAB</h4>
            <h6>Medical image labeling software for machine learning</h6>
        </div>
        <br><hr><br>
        <div class="row text-justify px-5 mt-4">
            <div class="col-sm-4">
                <h6>UPLOAD</h6>
                <hr>
                <p class="text-justify mt-3 text-sm-start fw-lighter fs-6">Upload files with the most common extensions, dicom files and video files, that will be included in specific annotation tasks.</p>
            </div>
            <div class="col-sm-4">
                <h6>VIEW</h6>
                <hr>
                <p class="text-justify mt-3 text-sm-start fw-lighter fs-6">Annotate objects in neatly presented files and effortlessly control displayed files in an assigned task.</p>
            </div>
            <div class="col-sm-4">
                <h6>ANNOTATE</h6>
                <hr>
                <p class="text-justify mt-3 text-sm-start fw-lighter fs-6">Label various files included in dedicated tasks thoroughly created by the administrator.</p>
            </div>
            <br><br>
        </div>
        <div class="row text-justify px-5 mt-4 mb-2">
            <div class="col-sm-4">
                <h6>EXPORT</h6>
                <hr>
                <p class="text-justify mt-3 text-sm-start fw-lighter fs-6">Easily export created annotations from dedicated administrator tab or through submitted labels view according to a chosen task or a file.</p>
            </div>
            <div class="col-sm-4">
                <h6>CONVERT</h6>
                <hr>
                <p class="text-justify mt-3 text-sm-start fw-lighter fs-6">Straightforwardly convert uploaded labels to PASCAL VOC XML, COCO JSON or YOLO annotation format. </p>
            </div>
            <div class="col-sm-4">
                <h6>CUSTOMIZE</h6>
                <hr>
                <p class="text-justify mt-3 text-sm-start fw-lighter fs-6">Comfortably modify your user profile information in case there is a need for change.</p>
            </div>
            <br><br>
        </div>
        <hr>
        <div class="d-flex justify-content-start px-5 py-5 mt-4">
            <p class="fw-lighter fs-6 mb-3"><i>Agata Polejowska, Gdansk University of Technology</i></p>
        </div>
    </div>
{% endblock %}

website/templates/admin-approve-requests.html
{% extends 'base.html' %}

{% block body %}
    <header>
        {% include 'includes/_navbar-admin.html' %}
    </header>
    <main>
        <div class="m-5">
            <table class="table  table-hover">
                <thead>
                    <tr>
                        <th scope="col"><small>ID</small></th>
                        <th scope="col"><small>USERNAME</small></th>
                        <th scope="col"><small>EMAIL</small></th>
                        <th scope="col"><small>DATE REQUESTED</small></th>
                        <th scope="col"><small>ACCESS</small></th>
                    </tr>
                </thead>
                <tbody>
                    {% for request in requests %}
                        {% if not request.approved %}    
                        <tr>
                            <th scope="row"><small>{{ request.id }}</small></th>
                            <td><small>{{ request.username }}</small></td>
                            <td><small>{{ request.email }}</small></td>
                            <td><small>{{ request.date_requested }}</small></td>
                            <td>
                                <a href="{{ url_for('admin.add_user', request_id=request.id) }}">
                                    <button class="btn btn-outline-dark btn-sm custom-control-button btn-approve" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Create a new user">APPROVE</button>
                                </a>          
                                <a href="{{ url_for('admin.remove_request', request_id=request.id) }}">
                                    <button class="btn btn-outline-dark btn-sm custom-control-button btn-deny mx-2" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Reject this request">DENY</button>
                                </a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-light" role="alert">{{ message }}</div>
                    {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>
{% endblock %}

{% block scripts %} 
{% endblock %}

website/templates/admin-create-task.html
{% extends 'base.html' %}

{% block body %}
    <header>
        {% include 'includes/_navbar-admin.html' %}
    </header>
    <main>
        <div class="container-fluid p-3 mb-5">
            <div class="card card-task bg-body mt-3 mx-5 p-3">
                <div class="d-flex justify-content-end">
                    <a href="{{ url_for('task.cancel_task', id=id) }}">
                        <button type="button" class="btn btn-outline-dark btn-sm custom-control-button btn-cancel mx-2">CANCEL</button>
                    </a>
                </div>
                <h5 class="card-title card-title-task px-2 mb-3">TASK #{{ id }}</h5>
                <form method="POST" enctype="multipart/form-data">
                    {{ form.hidden_tag() }} 
                    <div class="col-md-12 mt-4 px-2">
                        {{ form.name(class="form-control form-control-sm custom-form-control my-2 p-2 rounded-0") }}
                    </div>
                    <div class="row mb-5 mt-5 px-2">
                        <div class="col-md-4">
                            <input type="file" class="form-control form-control-sm rounded-0" name="files[]" multiple="true" autocomplete="off">     
                        </div>
                        <div class="col-md-4">
                            {{ form.select_camera(class="form-select form-select-sm rounded-0") }}
                            {{ form.select_camera.label(class="form-label-custom px-1") }}
                        </div>
                        <div class="col-md-2">
                            {{ form.select_frames(class="form-control form-control-sm rounded-0") }}
                            {{ form.select_frames.label(class="form-label-custom px-1") }}
                        </div>
                        <div class="col-md-2">
                            <div class="d-flex justify-content-end mr-2">
                                {{ form.upload(class="btn btn-dark btn-outline-light btn-upload rounded-0 px-5 py-1") }}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="col-md-12 mt-4 px-2">
                        <p class="text-sm-start fw-light px-1">Uploaded files:</p>
                        <ol class="list-group list-group-flush list-group-numbered">
                            {% for upload in uploads %}
                                <li class="list-group-item list-group-item d-flex justify-content-between align-items-center py-0">
                                    <p class="text-sm-start fw-lighter fs-6"><small>{{ upload }}</small></p>
                                </li>
                            {% endfor %}
                        </ol>
                    </div>
                    <hr>
                    <div class="col-md-12 mt-5 px-2">
                        <div class="row mt-4">
                            <div class="col-md-8">
                                {{ form.default_label(class="form-control form-control-sm custom-form-control my-2 px-2 rounded-0") }}
                            </div>
                            <div class="col-md-4">
                                <div class="d-flex justify-content-end mr-2">
                                    {{ form.add(class="btn btn-dark btn-outline-light btn-upload px-5 py-1 rounded-0") }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <ul class="list-group list-group-sm list-group-flush mt-3">
                                    {% for default_label in default_labels %}
                                        <li class="list-group-item text-sm rounded-0 py-0 my-0">
                                            <p class="text-sm-start fw-lighter fs-6 py-0"><small>{{ default_label }}</small></p>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        {{ form.create(class="btn btn-create mt-5 mb-3 px-5 py-1") }}
                    </div>
                    <hr>
                    {% include 'includes/_messages.html' %}
                </form>
            </div>
        </div>
    </main>
{% endblock %}

{% block scripts %} 
{% endblock %}

website/templates/admin-manage-tasks.html
{% extends 'base.html' %}

{% block body %}
<header>
    {% include 'includes/_navbar-admin.html' %}
</header>
<main>
    <div class="container-fluid p-3 mb-5">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="card card-task card-create-task mt-3 mx-5 p-3">
                {{ form.create(class="card-title card-create-task card-title-task") }}
            </div>
        </form>
        {% for task in tasks %}
            {% if task.status == 0 %}
            <div class="card card-task-inactive mt-3 mx-5 p-3">
            {% else %}
            <div class="card card-task bg-body mt-3 mx-5 p-3">
            {% endif %}
                <div class="row">
                    <div class="col-md-6">
                        <h5 class="card-title card-title-task">TASK #{{ task.id }}</h5>
                    </div>
                    <div class="col-md-6">
                        <div class="d-flex justify-content-end">
                            <a href="{{ url_for('user.task_files', username=current_user.username, task_id=task.id) }}">
                                <button type="button" class="btn btn-outline-dark btn-sm custom-control-button btn-cancel mx-2">
                                    CHECK DETAILS
                                </button>
                            </a>
                            <a href="{{ url_for('task.change_task_status', task_id=task.id, status=task.status) }}" style="color:black;">
                                <button type="button" class="btn btn-outline-dark btn-sm custom-control-button btn-cancel mx-2">
                                    {% if task.status == 0 %}
                                        ACTIVATE
                                    {% elif task.status == 1 %}
                                        DEACTIVATE
                                    {% else %}
                                        UNDEFINED STATUS
                                    {% endif %}
                                </button>
                            </a>
                            <a href="{{ url_for('task.remove_task', task_id=task.id) }}" style="color:black;">
                                <button type="button" class="btn btn-outline-dark btn-sm custom-control-button btn-cancel mx-2">
                                    REMOVE
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
                <p class="card-text">{{ task.name }}</p>
            </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

{% block scripts %} 
{% endblock %}

website/templates/admin-tasks-submitted-labels.html
{% extends 'base.html' %}

{% block body %}
    <header>
        {% include 'includes/_navbar-admin.html' %}
    </header>
    <main>
        <div class="container-fluid p-3 mb-5">
            {% for task in tasks %}
                <div class="card card-task bg-body mt-3 mx-5 p-3">
                    <a href="{{ url_for('export_convert.task_submitted_labels', task_id=task.id) }}" style="color:black;">
                        <div class="row">
                            <div class="col-md-6">
                                <h5 class="card-title card-title-task">TASK #{{ task.id }}</h5>
                            </div>
                            <div class="col-md-6">        
                                <div class="d-flex justify-content-end">
                                    <button type="button" class="btn btn-outline-light border border-dark btn-sm custom-control-button btn-cancel mx-2">
                                        CHECK SUBMITTED LABELS
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <p class="card-text">{{ task.name }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
    </main>
{% endblock %}

{% block scripts %} 
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/ico" href="{{ url_for('static', filename='img/favicon.ico') }}"/>
        <link href="{{ url_for('static', filename='styles/main.css') }}" rel="stylesheet" type="text/css">
        {% block style %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <title>ELMEDILAB</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
        {% block scripts %}
        {% endblock %}
    </body>
</html>

website/templates/user-label.html
{% extends 'base.html' %}

{% block body %}
    <header>
        {% if current_user.access == 2 %}
            {% include 'includes/_navbar-admin.html' %}
        {% else %}
            {% include 'includes/_navbar-user.html' %}
        {% endif %}
    </header>
    <main>
        <div class="row">
            {% include 'includes/_tools.html' %}
            {% include 'includes/_canvas.html' %}
            {% include 'includes/_labels.html' %}
        </div>  
    </main>
{% endblock %}

{% block scripts %} 
{% endblock %}

website/templates/user-main.html
{% extends 'base.html' %}

{% block body %}
    <header>
        {% if current_user.access == 2 %}
            {% include 'includes/_navbar-admin.html' %}
        {% else %}
            {% include 'includes/_navbar-user.html' %}
        {% endif %}
    </header>
    <main>
        <div class="container-fluid p-3 pb-5 mb-5">
            <a href="{{ url_for('user.tasks', username=current_user.username) }}">
                <div class="card card-admin-panel bg-body mt-3 mx-5 p-3">
                    <h5 class="card-title card-title-admin-panel">Search tasks</h5>
                </div>
            </a>
            <a href="{{ url_for('user.profile', username=current_user.username) }}">
                <div class="card card-admin-panel bg-body mt-4 mx-5 p-3">
                    <h5 class="card-title card-title-admin-panel">User profile</h5>
                </div>
            </a>
            <a href="{{ url_for('main.help') }}" >
                <div class="card card-admin-panel bg-body mt-4 mx-5 p-3">
                    <h5 class="card-title card-title-admin-panel">Help</h5>
                </div>
            </a>
            <a href="{{ url_for('main.about') }}" >
                <div class="card card-admin-panel bg-body mt-4 mx-5 p-3">
                    <h5 class="card-title card-title-admin-panel">About</h5>
                </div>
            </a>
        </div>
    </main>
{% endblock %}

{% block scripts %} 
{% endblock %}

website/templates/user-tasks.html
{% extends 'base.html' %}

{% block body %}
    <header>
        {% if current_user.access == 2 %}
            {% include 'includes/_navbar-admin.html' %}
        {% else %}
            {% include 'includes/_navbar-user.html' %}
        {% endif %}
    </header>
    <main>
        <div class="container-fluid p-3 pb-5 mb-5">
            {% for task in tasks %}
                {% if task.status == 1 %}
                    <a href="{{ url_for('user.task_files', username=current_user.username, task_id=task.id) }}">
                        <div class="card card-task my-3 mx-5 p-3 rounded-0">
                            <h5 class="card-title card-title-task">TASK #{{ task.id }}</h5>
                            <p class="card-text">{{ task.name }}</p>
                        </div>
                    </a>
                {% else %}
                    <div class="card card-task-inactive bg-body mt-3 mx-5 p-3">
                        <h5 class="card-title card-title-task">TASK #{{ task.id }}</h5>
                        <p class="card-text">{{ task.name }}</p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </main>
{% endblock %}

{% block scripts %} 
{% endblock %}