website/admin/routes.py
"""Mapping the admin URLs to the code rendering the web page."""

import os

from flask import render_template, redirect, url_for, Blueprint
from flask_login.utils import login_required

from website.task.routes import DIRECTORY_TASKS
from website.task.utils import remove_directory
from website.admin.utils import (
    add_new_user,
    configure_db_records,
    admin_access_required,
    remove_existing_user,
    remove_new_request,
)
from website.models import Request, User
from website import db


admin = Blueprint("admin", __name__)



@admin.route("/admin")
@login_required
@admin_access_required()
def admin_main():
    """The route to admin main panel.

    Returns:
        Renders admin-main.html template.
    """
    return render_template("admin-main.html")


@admin.route("/admin/requests", methods=["GET", "POST"])
@admin_access_required()
def approve_requests():
    """The route for approving requests.

    Returns:
        Renders template with requests management panel.
    """
    requests = Request.query.order_by(Request.date_requested)
    return render_template("admin-approve-requests.html", requests=requests)


@admin.route("/add-user/<int:request_id>")
@admin_access_required()
def add_user(request_id):
    """The route for adding new user.

    Args:
        request_id (int): The request unique identifier.

    Returns:
        Redirects to requests list.
    """
    request_approved = Request.query.get(request_id)
    request_approved.approved = True
    add_new_user(request_approved)
    remove_new_request(request_id)

    return redirect(url_for("admin.approve_requests"))


@admin.route("/admin/users")
@admin_access_required()
def users():
    """The route for managing users.

    Returns:
        Renders a page with users list.
    """
    users = User.query.order_by(User.date_added)
    return render_template("admin-users.html", users=users)


@admin.route("/remove-request/<int:request_id>")
@admin_access_required()
def remove_request(request_id):
    """The route for removing the request.

    Args:
        request_id (int): The request's unique identifier.

    Returns:
        Redirects to modified requests list.
    """
    remove_new_request(request_id)
    return redirect(url_for("admin.approve_requests"))


@admin.route("/admin/remove/<int:user_id>")
@admin_access_required()
def remove_user(user_id):
    """The route for removing the user.

    Args:
        user_id (int): The user's unique identifier.

    Returns:
        Redirects to modified users list.
    """
    remove_existing_user(user_id)
    return redirect(url_for("admin.users"))


@admin.route("/admin/restart-db")
@admin_access_required()
def admin_restart_db():
    """The route for restarting the database.

    Returns:
        Renders admin main panel template.
    """
    db.drop_all()
    db.create_all()
    configure_db_records()
    remove_directory(os.path.abspath(DIRECTORY_TASKS))
    return render_template("admin-main.html")

website/main/routes.py
from flask import render_template, redirect, url_for, Blueprint
from flask_login.utils import login_required


main = Blueprint("main", __name__)


@main.route("/")
def base():
    """The route for redirecting to the login page."""
    return redirect(url_for("auth.index"))


@main.route("/help")
@login_required
def help():
    """The route for rendering help page template."""
    return render_template("help.html")


@main.route("/about")
@login_required
def about():
    """The route for rendering about page template."""
    return render_template("about.html")

website/user/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required

from website.models import FILE_STATUS, Annotation, Task, Upload, User
from website.user.utils import get_uploads_id
from website.user.forms import UpdateAccountForm
from website import db


user = Blueprint("user", __name__)


@user.route("/user-<string:username>")
@login_required
def user_main(username):
    """The route for main user panel.

    Args:
        username (str): The username.

    Returns:
        Renders a page with user panel displaying available options.
    """
    return render_template("user-main.html")


@user.route("/user-<string:username>/profile", methods=["GET", "POST"])
@login_required
def profile(username):
    """The route for user profile form.

    Args:
        username (str): The username.
    Returns:
        Renders a page with user profile.
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.country = form.country.data
        current_user.education = form.education.data
        current_user.profession = form.profession.data
        current_user.additional_details = form.additional_details.data
        db.session.commit()
        flash("Changes have been saved successfully.", "success")
        return redirect(url_for("user.profile", username=username))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.country.data = current_user.country
        form.education.data = current_user.education
        form.profession.data = current_user.profession
        form.additional_details.data = current_user.additional_details
    return render_template("user-profile.html", form=form)


@user.route("/user-<string:username>/tasks")
@login_required
def tasks(username):
    """The route for the list of tasks.

    Args:
        username (str): The username.

    Returns:
        Renders the template with tasks.
    """
    tasks = Task.query.order_by(Task.status.desc())
    return render_template("user-tasks.html", tasks=tasks, mode="closed")


@user.route("/user-<string:username>/task-<int:task_id>/files")
@login_required
def task_files(username, task_id):
    """"The route dedicated for files included in a task operations.

    Args:
        username (str): The username.
        task_id (int): The task unique identifier.

    Returns:
        Renders a page with files included in a chosen task.
    """
    task_status = Task.query.filter(Task.id == task_id).first().status
    if not task_status:
        return redirect(url_for("user.tasks", username=username))

    uploads_id = get_uploads_id(task_id)
    uploads_entries = []
    upload_annotations_num = {}
    for upload_id in uploads_id:
        upload = Upload.query.filter(Upload.id == upload_id).first()
        annotations_num = len(
            Annotation.query.filter_by(task_id=task_id, filename=upload.name).all()
        )
        upload_annotations_num[upload.name] = annotations_num
        if upload.status == FILE_STATUS["CLOSED"]:
            pass
        elif upload.status == FILE_STATUS["IN PROGRESS"]:
            pass
        else:
            if annotations_num == 0:
                upload.status = FILE_STATUS["NEW"]
            if annotations_num > 0:
                upload.status = FILE_STATUS["ANNOTATED"]
        uploads_entries.append(upload)
        db.session.commit()

    if current_user.access == 2:
        return render_template(
            "task-details.html",
            files=uploads_entries,
            task_id=task_id,
            upload_annotations_num=upload_annotations_num
        )

    return render_template(
        "task-files.html",
        files=uploads_entries,
        task_id=task_id,
        upload_annotations_num=upload_annotations_num,
    )


@user.route("/user-profile/<string:username>")
@login_required
def display_user_profile(username):
    """The route for the other than the current user user profile page.

    Args:
        username (str): The username of the user which profile is selected.

    Returns:
        Renders the page with the user profile.
    """
    user = User.query.filter_by(username=username).first()
    return render_template("user-profile-external.html", user=user, username=username)

website/templates/includes/_labels.html
<div id="main-labels" class="col-md-3 mt-4">
    <hr>
    <div class="config-group-flush mb-2">
    {% for label in labels|reverse %}
        {% if not label.name %}
            <div class="row mb-3 mt-2 mx-1 px-2 custom-labels-header">
                <div class="py-2">
                    Label number created in this session: {{ label.nr }}
                </div>
            </div>
            <form method="POST">
                <div class="row mx-2 mt-1 p-2">
                    <div class="form-check text-wrap text-break label-text mt-1">
                        <input class="form-check-input rounded-0" type="radio" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }" name="flexRadioDefault" id="predefined-label-name-radiobutton">
                        <label class="form-check-label mb-2" for="predefined-label-name-radiobutton">
                            Use a predefined class for the object's name
                        </label>
                        <select id="predefined-label-name" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }" class="form-select form-select-sm label-text rounded-0" aria-label=".form-select-sm">
                            {% for predefined_label in predefined_labels %}
                                <option value="">{{ predefined_label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-check text-wrap text-break label-text mt-3">
                        <input class="form-check-input rounded-0" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }" type="radio" name="flexRadioDefault" id="input-label-name-radiobutton" checked>
                        <label class="form-check-label mb-2" for="input-label-name-radiobutton">
                            Define the object's name
                        </label>
                        <input name="{{ label.nr }}" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }" type="text" class="input-label-name form-control form-control-sm label-text mt-1 rounded-0" placeholder="Name" aria-label=".form-control-sm" spellcheck="false" autofocus></input>
                    </div>
                </div>
                <hr>
                <div class="row m-2 mt-1 p-2 pt-1">
                    <div class="form-check text-wrap text-break label-text">
                        <label class="form-check-label mb-1" for="">Define the object's pose</label>
                        <input name="{{ label.pose }}" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }" class="input-label-pose form-control form-control-sm label-text mt-1 rounded-0" type="text" placeholder="Unspecified" aria-label=".form-control-sm"></input>
                    </div>
                </div>
                <hr>
                <div class="row mx-3 mt-1 px-3">
                    <div class="form-check text-wrap text-break label-text">
                        <input class="form-check-input rounded-0" type="checkbox" value="0" id="truncated" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }">
                        <label class="form-check-label" for="truncated">Truncated</label>
                    </div>
                    <div class="form-check text-wrap text-break label-text">
                        <input class="form-check-input rounded-0" type="checkbox" value="0" id="difficult" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }">
                        <label class="form-check-label"for="difficult">Difficult</label>
                    </div>
                    <div class="form-check text-wrap text-break label-text">
                        <input class="form-check-input rounded-0" type="checkbox" value="0" id="occluded" onkeydown="if (event.keyCode == 13) { label('{{ label.nr|safe }}'); }">
                        <label class="form-check-label"for="occluded">Occluded</label>
                    </div>
                </div>
                <div class="row mb-3 mt-3 mx-1">
                        <button type="button" class="btn btn-sm btn-dark text-center custom-labels-header rounded-0 px-3" onclick="label('{{ label.nr|safe }}');">
                            SAVE TO A SESSION
                        </button>
                </div>
            </form>
        {% endif %}
    {% endfor %}
    </div>
    <div class="row mt-2">
            {% if labels and labels|length >= 1 %}
            <hr>
                <p><small>Annotations created in this session</small></p>
                <ul class="list-group-flush px-0">
                {% for label in labels|reverse %}
                    {% if label.name %}
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                        <div class="col-md-4 text-wrap text-break label-text">
                            <div class="input-group">
                                {{ label.nr }}
                                {{ label.name }}
                            </div>
                        </div>
                        <div>
                            <button id="{{ label.nr }}" type="button" class="btn btn-outline-dark btn-sm custom-list-button" 
                            onclick="window.location.replace('/user-' + username + '/task-' + task_id + '/file-' + file_id + '/remove-from-session/' + this.id)">
                                REMOVE
                            </button>
                        </div>
                    </li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endif %}
        </div>
        {% if labels and labels|length >= 1 %}
            <div class="col-md-12">
                <div class="d-flex justify-content-center custom-labels-header mx-2">
                    <a href="{{ url_for('labeling.submit_labels', username=current_user.username, task_id=task_id, file_id=file_id) }}">
                        <button type="button" class="btn btn-sm btn-dark btn-label-submit text-center rounded-0 px-5 mx-1" style="background-color: black;" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Send session annotations to the database">
                            <small>SUBMIT ANNOTATIONS</small>
                        </button>
                    </a>
                </div>
                <hr>
            </div>
        {% endif %}
        <div>
            {% if annotations %}
                <p><small>Annotations saved to the database</small></p>
                <ul class="list-group-flush px-0">
            {% for annotation in annotations|reverse %}
                {% if annotation.name %}
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
                        <div class="col-md-4 text-wrap text-break label-text">
                            <a href="{{ url_for('labeling.annotation_information', annotation_id=annotation.id) }}" target="_blank" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Click to see information about this annotation">
                                <div class="input-group text-dark annotation-info">
                                    {{ annotation.id }}
                                    {% if annotation.name %}
                                        {{ annotation.name }}
                                    {% endif %} 
                                </div>
                            </a>
                        </div>
                        <div>
                            <a href="{{ url_for('user.display_user_profile', username=annotation.creator) }}" target="_blank">
                                <button class="btn btn-outline-dark btn-sm custom-list-button" data-bs-placement="left" title="View the creator profile">
                                    {{ annotation.creator }}
                                </button>
                            </a>
                        </div>
                        <div>
                            <button id="{{ annotation.id }}" type="button" class="btn btn-outline-dark btn-sm custom-list-button" data-bs-placement="left" title="Show or hide annotation on canvas"
                            onclick="showHideOneLabel('{{ annotation.id|safe }}', '{{ annotation.x_min|safe }}', '{{ annotation.x_max|safe }}', '{{ annotation.y_min|safe }}', '{{ annotation.y_max|safe }}' )">
                                SHOW
                            </button>
                        </div>
                        |
                        <div>
                            <button id="{{ annotation.id }}" type="button" class="btn btn-outline-dark btn-sm custom-list-button" data-bs-placement="left" title="Remove this annotation from the database"
                            onclick="window.location.replace('/user-' + username + '/task-' + task_id + '/file-' + file_id + '/remove-from-db/' + this.id)">
                                REMOVE
                            </button>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
    <script>
        function getInputNameValue() {
            var inputNameValue = '';
            
            if (document.getElementById('predefined-label-name-radiobutton').checked) {
                var selectNameOptions = document.getElementById("predefined-label-name")
                inputNameValue = selectNameOptions.options[selectNameOptions.selectedIndex].text;
            }
            if (document.getElementById('input-label-name-radiobutton').checked) {
                inputNameValue  = document.getElementsByClassName("input-label-name")[0].value;
            }

            return inputNameValue;
        }

        function getPoseValue() {
            var inputPoseValue = document.getElementsByClassName("input-label-pose")[0].value;
            return inputPoseValue;
        }

        function checkCheckbox(id) {
            if (document.getElementById(id).checked) {
                return '1';
            } 
            else {
                return '0';
            }
        }

        var label = function(nr, name=getInputNameValue(), 
                            pose=getPoseValue(), 
                            occluded=checkCheckbox('occluded'),
                            difficult=checkCheckbox('difficult'), 
                            truncated=checkCheckbox('truncated')) {
            window.location.replace(
                "/user-" + username +
                "/task-" + task_id +
                "/file-" + file_id +
                "/label/open/" + nr +
                "?name=" + name +
                "&pose=" + pose +
                "&difficult=" + difficult +
                "&occluded=" + occluded +
                "&truncated=" + truncated
                );
        }

        function showHideOneLabel(annotation_id, xMin, xMax, yMin, yMax) {
            console.log("Show:", xMin, xMax, yMin, yMax);
            ctx.strokeStyle = 'blue';
            ctx.lineWidth = 1;
            ctx.rect(xMin, yMin, xMax - xMin, yMax - yMin);
            ctx.stroke();

            if (document.getElementById(annotation_id).innerText == 'SHOW') {
                document.getElementById(annotation_id).disabled = true;
            }
        }
    </script>
</div>

website/templates/includes/_messages.html
<div class="col-md-12 pt-3">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} custom-alert rounded-0 p-2">
                    <small>{{ message }}</small>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>

website/templates/includes/_navbar-admin.html
<div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4 toggle-brand custom-nav-text">
        <h5 class="text-white h5">Medical image labeling software for machine learning</h5>
        <span><a href="{{ url_for('main.about') }}" class="text-muted">About</a></span>
    </div>
</div>
<nav class="navbar sticky-top navbar-dark bg-dark" id="main-navbar">
    <div class="container-fluid">
        <a href="{{ url_for('admin.admin_main') }}">
            <h5 class="text-white brand-heading h5">ELMEDILAB</h5>       
        </a>
        <div class="dropdown">
            <button class="btn btn-secondary btn-sm help-btn mr-0" type="button">
                <span class="text-muted"><a href="{{ url_for('main.help') }}" class="custom-nav-text">Help</a></span>
            </button>
            <button class="btn btn-secondary dropdown-toggle btn-sm user-btn" type="button" data-bs-toggle="dropdown">
                <a href="#"><span class="custom-nav-text">admin</span></a>
            </button>
            <ul class="dropdown-menu custom-dropdown">
                <li><a class="dropdown-item" href="{{ url_for('admin.admin_main') }}">ADMIN PANEL</a></li>
                <li><a class="dropdown-item" href="{{ url_for('user.user_main', username=current_user.username) }}">USER PANEL</a></li>
                <div class="dropdown-divider"></div>
                <li><a class="dropdown-item" href="{{ url_for('task.manage_tasks') }}">MANAGE TASKS</a></li>
                <li><a class="dropdown-item" href="{{ url_for('admin.approve_requests') }}">REQUESTS APPROVAL</a></li>
                <li><a class="dropdown-item" href="{{ url_for('admin.users') }}">USERS</a></li>
                <li><a class="dropdown-item" href="{{ url_for('export_convert.tasks_submitted_labels') }}">SUBMITTED LABELS</a></li>
                <li><a class="dropdown-item" href="{{ url_for('export_convert.export_labels') }}">EXPORT LABELS</a></li>
                <li><a class="dropdown-item" href="{{ url_for('export_convert.convert_labels') }}">CONVERT LABELS FORMAT</a></li>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">LOG OUT</a>
            </ul>
        </div>
    </div>
</nav>

website/templates/includes/_navbar-user.html
<div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4 toggle-brand custom-nav-text">
        <h5 class="text-white h5">Medical image labeling software for machine learning</h5>
        <span><a href="{{ url_for('main.about') }}" class="text-muted">About</a></span>
    </div>
</div>
<nav class="navbar sticky-top navbar-dark bg-dark" id="main-navbar">
    <div class="container-fluid">
        <a href="{{ url_for('user.user_main', username=current_user.username) }}">
            <h5 class="text-white brand-heading h5">ELMEDILAB</h5>
        </a>
        <div class="dropdown">
            <button class="btn btn-secondary btn-sm help-btn mr-0" type="button">
                <span class="text-muted"><a href="{{ url_for('main.help') }}" class="custom-nav-text">Help</a></span>
            </button>
            <button class="btn btn-secondary dropdown-toggle btn-sm user-btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown">
                <a href="#"><span class="custom-nav-text">{{ current_user.username }}</span></a>
            </button>
            <ul class="dropdown-menu custom-dropdown" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{{ url_for('user.user_main', username=current_user.username) }}">USER PANEL</a></li>
                <div class="dropdown-divider"></div>
                <li><a class="dropdown-item" href="{{ url_for('user.profile', username=current_user.username) }}">USER PROFILE</a></li>
                <li><a class="dropdown-item" href="{{ url_for('user.tasks', username=current_user.username, mode='closed') }}">SEARCH TASKS</a></li>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">LOG OUT</a>
            </ul>
          </div>
    </div>
</nav>

website/templates/includes/_tools.html
<div id="tools-div" class="col-md-1 text-center my-4 pl-2 pr-2">
    <hr>
    <div class="row mt-4">
        <button id="zoom" onclick="zoomAndDragMode()" type="submit" class="btn btn-block btn-dark p-1 px-2 m-1 rounded-0 custom-tools-btn" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Enable zooming and dragging the image across the canvas">
            Zoom and drag enable
        </button>
    </div>
    <div class="row mb-4">
        <div class="btn btn-block btn-dark p-1 py-2 mx-1 mt-3 mb-0 rounded-0 custom-tools-btn-bbox" onclick="enableLabelMode()" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Enable creating a new annotation on the canvas">
            Bbox
        </div>
            <div class="p-1 mx-1 mt-2 mb-1 rounded-0 custom-tools-btn" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Change the color of the bounding box"> 
                <select onchange="resetColor()" id="color-select" class="form-select form-select-sm label-text custom-select" aria-label=".form-select-sm">
                    <option class="custom-color-option" value='#000000'>Black</option>
                    <option class="custom-color-option" value='#FFFFFF'>White</option>
                    <option class="custom-color-option" value='#4876FF'>Blue</option>
                    <option class="custom-color-option" value='#B0171F'>Red</option>
                    <option class="custom-color-option" value='#FFFF00'>Yellow</option>
                </select>
            </div>
            <div class="p-1 mx-1 mb-1 rounded-0 custom-tools-btn" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Change the line width of the bounding box"> 
                <select onchange="resetLineWidth()" id="line-width-select" class="form-select form-select-sm label-text custom-select" aria-label=".form-select-sm">
                    <option class="custom-option" value='1'>Line width: 1</option>
                    <option class="custom-option" value='2'>Line width: 2</option>
                    <option class="custom-option" value='3'>Line width: 3</option>
                    <option class="custom-option" value='4'>Line width: 4</option>
                </select>
            </div>
    </div>
    <div class="row mt-4">
        <button id="btn_coordinates" onclick="showCursorCoordinates()" type="submit" class="btn btn-block btn-dark p-1 px-2 m-1 rounded-0 custom-tools-btn" tardata-bs-toggle="tooltip" data-bs-placement="right" title="Hide displaying coordinates below">
            Hide cursor coordinates
        </button>
    </div>
    <div id="coordinates" class="justify-content-evenly text-center">
        <table id="img_data" class="table table-sm table-borderless align-middle">
        </table>
    </div>
    <hr>
</div>